### ISSUE TITLE
fix for df command

### ISSUE THREAD

**Issue by benaryorg** [overflowerror/MinervaBot#3]
would `sed s/\s+/\s/g` work too?

**Comment by sigmasternchen** [comment]
I'm not getting the same result. I'm trying to remove all double whitespaces.

**Comment by benaryorg** [comment]
This should work actually.

``` bash
$ df -h --output=source,size,used | grep /dev/ | sed 's/\s\+/;/g'
/dev/sda1;231M;6.5M
/dev/sda3;64G;30G
/dev/sdb;932G;444M
```

Sorry, I forgot the backslash in the issue.
